[package]
name = "flex_ic"
version = "0.1.0"
edition = "2024"

[dependencies]
can-dbc = "6.0.0"
raylib = "5.5.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
socketcan = "3.5.0"
