use std::io::{Error, Write};
use std::fs::File;
use std::process::{Command, Stdio};

use can_dbc::DBC;


const VEHICLE_C: &str = "vehicle.c";
const VEHICLE_H: &str = "vehicle.h";
const DBC_RAW: &str = "parsed_dbc.raw";

const AUTO_GENERATED_STAMP: &str =
r#"/*
    ========================================================================================
     THIS CODE HAS BEEN AUTO-GENERATED BY THE FAST_DBC_TO_C RUST TOOL.

        *~*~*~* DO NOT MODIFY THIS UNLESS YOU KNOW PRECISELY WHAT YOU ARE DOING. *~*~*~*


    @#@#@ PROJECT LICENSE @#@#@

    MIT License

    Copyright (c) 2025 Zack Puhl <github@xmit.xyz>

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.


      +++
      +++ Git Hash: {}
    ========================================================================================
*/

"#;


pub fn generate_from_dbc(into_dir: &str, dbc: &DBC) -> Result<(), Error>
{
    dbg!(&dbc);

    // Write the debug dump of the parsed DBC file to a file adjacent to other generated artifacts.
    let mut raw_file = File::create(&format!("{}/{}", into_dir, DBC_RAW))?;
    raw_file.write_all(&format!("{:#?}", dbc).as_bytes())?;

    // Let the magic begin...
    let mut src_file = File::create(&format!("{}/{}", into_dir, VEHICLE_C))?;
    let mut hdr_file = File::create(&format!("{}/{}", into_dir, VEHICLE_H))?;

    let timestamp = Command::new("date").arg("+%s").output()?.stdout;
    let git_hash = Command::new("git").arg("rev-parse").arg("HEAD").output()?.stdout;
    src_file.write_all(AUTO_GENERATED_STAMP.as_bytes())?;
    src_file.write_all(format!("// Generation timestamp: {}\n// Git Hash: {}\n\n\n", timestamp, git_hash).as_bytes())?;
    hdr_file.write_all(AUTO_GENERATED_STAMP.as_bytes())?;
    src_file.write_all(format!("// Generation timestamp: {}\n// Git Hash: {}\n\n\n", timestamp, git_hash).as_bytes())?;

    Ok(())
}
