#!/usr/bin/env python3
import sys
import json


if len(sys.argv) < 3:
    sys.exit(f"USAGE: {sys.argv[0]} {{widgets-conf-json}} {{gen-c-file}}")

in_json = sys.argv[1]
out_conf = sys.argv[2]

print(f"Processing JSON widgets configuration at '{in_json}'...")

with open(in_json, 'r') as in_conf:
    conf_dict = json.load(in_conf)

print(conf_dict)

with open(out_conf, 'w') as out_c:
    print("[truncated out-file]")
    out_c.write(
"""/*
    ========================================================================================
     THIS CODE HAS BEEN AUTO-GENERATED BY THE CONFIG_SRC_GEN PYTHON SCRIPT.

        *~*~*~* DO NOT MODIFY THIS UNLESS YOU KNOW PRECISELY WHAT YOU ARE DOING. *~*~*~*


    @#@#@ PROJECT LICENSE @#@#@

    MIT License

    Copyright (c) 2025 Zack Puhl <github@xmit.xyz>

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.

    ========================================================================================
*/
const char *WIDGETS_CONFIGURATION =
"""
    )


for widget in conf_dict:
    can_signal_names = ":".join([f"{widget['can_message_name']}_{x}" for x in widget['can_signal_names']])
    widget_label = widget['label']
    type_and_skin = f"{widget['type']}:{(widget['skin'] or 'default')}"
    visible = "yes" if widget['visible'] else "no"
    orientation = f"{widget['position']['x']},{widget['position']['y']},{widget['dimensions']['width']},{widget['dimensions']['height']}"
    opts_str = "placeholder"   # TODO!

    with open(out_conf, 'a') as out_c:
        out_c.write(
            f"    \"{can_signal_names},{widget_label},{type_and_skin},{visible},{orientation},{widget['z_index']},"
            + f"{opts_str}\\n\"\n"
        )


with open(out_conf, 'a') as out_c:
    out_c.write(";")

print("Config source generation complete!\n")
exit(0)
